doctrine:
  dbal:
    default_connection: superset
    connections:
      superset:
        url: '%env(resolve:SUPERSET_DATABASE_URL)%'

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    default_entity_manager: superset
    entity_managers:
      superset:
        connection: superset
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          HydraSupersetBundle:
            type: attribute
            is_bundle: false
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'Hydra\SupersetBundle\Entity'
    controller_resolver:
      auto_mapping: false
