doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:SUPERSET_DATABASE_URL)%'

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
          HydraSupersetBundle:
            is_bundle: true
            type: attribute
            dir: 'src/Entity'
            prefix: 'Hydra\SupersetBundle\Entity'
    controller_resolver:
      auto_mapping: false
