<?php

declare(strict_types=1);

namespace HydraSupersetBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250103090349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create caop & pays tables with their relations';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE caop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, marque VARCHAR(255) NOT NULL, lp VARCHAR(255) NOT NULL, sais_vente VARCHAR(255) NOT NULL, magasin_pf_apres_bp VARCHAR(255) NOT NULL, qte INT NOT NULL, brut_devise NUMERIC(10, 2) NOT NULL, montant_en_devise NUMERIC(10, 2) NOT NULL, devise_piece VARCHAR(255) NOT NULL, montant_en_euro NUMERIC(10, 2) NOT NULL, brut_euro NUMERIC(10, 2) NOT NULL, devise_euro VARCHAR(255) NOT NULL, date_piece DATE NOT NULL, type_doc VARCHAR(255) NOT NULL, no_piece INT NOT NULL, forme VARCHAR(255) NOT NULL, modele VARCHAR(255) NOT NULL, tp_conso VARCHAR(255) NOT NULL, ligne_ext VARCHAR(255) NOT NULL, pu_brut_eur NUMERIC(10, 2) NOT NULL, pu_brut_dev NUMERIC(10, 2) NOT NULL, groupe VARCHAR(255) DEFAULT NULL, made_in VARCHAR(2) NOT NULL, pays VARCHAR(2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F3A220B2AD3A0D24 ON caop (made_in)');
        $this->addSql('CREATE INDEX IDX_F3A220B2349F3CAE ON caop (pays)');
        $this->addSql('CREATE TABLE pays (code INT NOT NULL, alpha2 VARCHAR(2) NOT NULL, alpha3 VARCHAR(3) NOT NULL, nom_en_gb VARCHAR(45) NOT NULL, nom_fr_fr VARCHAR(45) NOT NULL, PRIMARY KEY(alpha2))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_349F3CAE77153098 ON pays (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_349F3CAEC065E6E4 ON pays (alpha3)');
        $this->addSql('ALTER TABLE caop ADD CONSTRAINT FK_F3A220B2AD3A0D24 FOREIGN KEY (made_in) REFERENCES pays (alpha2) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE caop ADD CONSTRAINT FK_F3A220B2349F3CAE FOREIGN KEY (pays) REFERENCES pays (alpha2) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE caop DROP CONSTRAINT FK_F3A220B2AD3A0D24');
        $this->addSql('ALTER TABLE caop DROP CONSTRAINT FK_F3A220B2349F3CAE');
        $this->addSql('DROP TABLE caop');
        $this->addSql('DROP TABLE pays');
    }
}
