services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hydra\SupersetBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'

  Hydra\SupersetBundle\Service\FileProcessor:
    public: true
    arguments:
      $entityManager: '@doctrine.orm.superset_entity_manager'
      $dir: '%kernel.project_dir%/public/uploads/Superset'

  Hydra\SupersetBundle\Command\CaopImportCommand:
    tags:
      - { name: 'console.command', command: 'superset:caop:import' }
      - { name: 'console.command', command: 'su:ca:im' }
      - { name: 'console.command', command: 's:c:i' }
